"use client";

import { useEffect, useMemo, useState } from "react";

type Mode = "home" | "era" | "perfect" | "player" | "about";
type Game = Exclude<Mode, "home" | "about">;
type Pos = "GK" | "DEF" | "MID" | "ATT";
type Player = { id:string; name:string; pos:Pos; era:string; nation:string; club:string; league:string; attrs:number[]; color:string; tags:string[]; timeless:boolean };
type Pick = Player & { slot?:string; attribute?:string; value?:number };
type MatchResult = { result:"W"|"D"|"L"; score:string; opponent:string; summary:string; tone:string };
type Coach = {name:string;era:string;attack:string;defence:string;pressing:string;tag:string;attackMod:number;defenceMod:number;cleanSheetMod:number;quote:string};
type LeagueSeason = {league:string;year:number;powerhouses:string[];story:string};
type TableRow = {club:string;played:number;wins:number;draws:number;losses:number;gf:number;ga:number;gd:number;points:number;highlight?:boolean};
type Result = { title:string; score:number; grade:string; story:string; stats:{label:string;value:string}[]; badges:string[]; detail:string[]; matches?:MatchResult[]; table?:TableRow[]; awards?:string[]; review?:{label:string;value:string;copy:string}[] };

const A = ["PAC","FIN","PAS","DRI","DEF","PHY"];
const COLORS = ["#e6ff52","#ff6b35","#63e6ff","#d9a8ff","#ffcf4a"];
const raw: Array<[string,Pos,string,string,string,string,number[]]> = [
  ["Gianluigi Buffon","GK","2000–04","Italy","Turin","Serie A",[55,28,72,58,97,91]],
  ["Manuel Neuer","GK","2010–14","Germany","Munich","Bundesliga",[78,32,88,72,96,88]],
  ["Peter Schmeichel","GK","1995–99","Denmark","Manchester","Premier League",[58,25,65,48,95,94]],
  ["Iker Casillas","GK","2005–09","Spain","Madrid","La Liga",[68,22,70,61,96,84]],
  ["Edwin van der Sar","GK","2005–09","Netherlands","Manchester","Premier League",[52,24,79,59,94,87]],
  ["Paolo Maldini","DEF","1990–94","Italy","Milan","Serie A",[86,60,84,82,98,91]],
  ["Franz Beckenbauer","DEF","Legacy","Germany","Munich","Bundesliga",[80,72,93,88,97,84]],
  ["Virgil van Dijk","DEF","2015–19","Netherlands","Liverpool","Premier League",[82,58,82,74,96,96]],
  ["Sergio Ramos","DEF","2010–14","Spain","Madrid","La Liga",[82,76,84,79,94,92]],
  ["Sergio Ramos","DEF","2005–09","Spain","Madrid","La Liga",[86,68,76,75,86,88]],
  ["Cafu","DEF","2000–04","Brazil","Rome","Serie A",[94,68,86,88,89,87]],
  ["Roberto Carlos","DEF","1995–99","Brazil","Madrid","La Liga",[97,86,82,87,86,91]],
  ["Philipp Lahm","DEF","2010–14","Germany","Munich","Bundesliga",[85,63,92,90,95,78]],
  ["Rio Ferdinand","DEF","2005–09","England","Manchester","Premier League",[83,50,82,74,94,90]],
  ["Carles Puyol","DEF","2005–09","Spain","Barcelona","La Liga",[74,58,76,67,96,95]],
  ["Zinedine Zidane","MID","2000–04","France","Madrid","La Liga",[80,90,98,97,61,86]],
  ["Xavi","MID","2005–09","Spain","Barcelona","La Liga",[70,82,99,94,74,72]],
  ["Andrés Iniesta","MID","2010–14","Spain","Barcelona","La Liga",[78,84,97,98,66,70]],
  ["Luka Modrić","MID","2015–19","Croatia","Madrid","La Liga",[78,82,97,95,79,79]],
  ["Patrick Vieira","MID","2000–04","France","London","Premier League",[84,78,88,84,94,97]],
  ["Andrea Pirlo","MID","2005–09","Italy","Milan","Serie A",[65,81,99,91,68,72]],
  ["Kevin De Bruyne","MID","2020–24","Belgium","Manchester","Premier League",[77,90,98,91,67,86]],
  ["Kaká","MID","2005–09","Brazil","Milan","Serie A",[93,91,92,95,62,84]],
  ["Claude Makélélé","MID","2000–04","France","London","Premier League",[76,59,86,82,97,89]],
  ["Jude Bellingham","MID","2020–24","England","Madrid","La Liga",[88,88,91,92,83,93]],
  ["Lionel Messi","ATT","2010–14","Argentina","Barcelona","La Liga",[94,99,98,99,42,78]],
  ["Lionel Messi","ATT","2005–09","Argentina","Barcelona","La Liga",[97,91,88,98,38,72]],
  ["Cristiano Ronaldo","ATT","2010–14","Portugal","Madrid","La Liga",[97,99,88,96,45,97]],
  ["Cristiano Ronaldo","ATT","2005–09","Portugal","Manchester","Premier League",[98,91,84,97,44,91]],
  ["Thierry Henry","ATT","2000–04","France","London","Premier League",[98,97,89,96,48,86]],
  ["Ronaldo Nazário","ATT","1995–99","Brazil","Milan","Serie A",[99,98,84,99,42,92]],
  ["Ronaldinho","ATT","2005–09","Brazil","Barcelona","La Liga",[91,93,96,99,44,80]],
  ["Robert Lewandowski","ATT","2015–19","Poland","Munich","Bundesliga",[84,98,87,91,48,93]],
  ["Kylian Mbappé","ATT","2020–24","France","Paris","Ligue 1",[99,96,86,97,43,88]],
  ["Mohamed Salah","ATT","2015–19","Egypt","Liverpool","Premier League",[96,95,88,94,49,84]],
  ["Dennis Bergkamp","ATT","1995–99","Netherlands","London","Premier League",[81,94,96,97,46,82]],
  ["Karim Benzema","ATT","2020–24","France","Madrid","La Liga",[82,97,93,94,48,89]],
  ["Nick Pope","GK","2020–24","England","Newcastle","Premier League",[49,20,67,45,84,86]],
  ["David Raya","GK","2020–24","Spain","London","Premier League",[62,18,82,61,86,78]],
  ["Steve Mandanda","GK","2010–14","France","Marseille","Ligue 1",[58,22,70,55,82,83]],
  ["Dan Burn","DEF","2020–24","England","Newcastle","Premier League",[54,49,70,61,84,92]],
  ["Trent Alexander-Arnold","DEF","2015–24","England","Liverpool","Premier League",[82,73,96,86,78,76]],
  ["James Tarkowski","DEF","2020–24","England","Liverpool","Premier League",[58,52,68,57,86,91]],
  ["Nacho Monreal","DEF","2015–19","Spain","London","Premier League",[72,61,77,73,82,78]],
  ["Wes Morgan","DEF","2015–19","Jamaica","Leicester","Premier League",[55,52,61,49,84,94]],
  ["Cristian Zaccardo","DEF","2005–09","Italy","Palermo","Serie A",[69,55,70,64,81,83]],
  ["Pascal Groß","MID","2020–24","Germany","Brighton","Premier League",[59,76,88,81,72,76]],
  ["James Milner","MID","2015–19","England","Liverpool","Premier League",[72,73,82,77,80,91]],
  ["Mousa Dembélé","MID","2015–19","Belgium","London","Premier League",[78,70,84,92,81,90]],
  ["Mark Noble","MID","2010–14","England","London","Premier League",[62,73,82,75,78,82]],
  ["Gennaro Gattuso","MID","2005–09","Italy","Milan","Serie A",[70,62,76,72,91,96]],
  ["Tim Cahill","MID","2005–09","Australia","Liverpool","Premier League",[72,83,76,74,75,94]],
  ["Olivier Giroud","ATT","2015–19","France","London","Premier League",[66,88,81,79,50,93]],
  ["Peter Crouch","ATT","2005–09","England","Liverpool","Premier League",[58,82,74,70,46,88]],
  ["Michu","ATT","2010–14","Spain","Swansea","Premier League",[72,86,75,79,48,83]],
  ["Jamie Vardy","ATT","2015–19","England","Leicester","Premier League",[94,88,73,82,49,86]],
  ["Aritz Aduriz","ATT","2015–19","Spain","Bilbao","La Liga",[61,87,72,74,48,92]],
  ["Demba Ba","ATT","2010–14","Senegal","Newcastle","Premier League",[79,84,71,77,47,90]],
  ["Keylor Navas","GK","2015–19","Costa Rica","Madrid","La Liga",[64,20,72,57,88,80]],
  ["Brad Friedel","GK","2005–09","USA","Blackburn","Premier League",[48,18,62,43,84,89]],
  ["Yann Sommer","GK","2015–19","Switzerland","Gladbach","Bundesliga",[61,19,78,59,86,76]],
  ["Fabien Barthez","GK","1995–99","France","Monaco","Ligue 1",[70,23,73,64,87,75]],
  ["Branislav Ivanović","DEF","2010–14","Serbia","London","Premier League",[70,65,72,65,87,93]],
  ["Diego Godín","DEF","2010–14","Uruguay","Madrid","La Liga",[66,61,70,58,91,92]],
  ["Javier Zanetti","DEF","2000–04","Argentina","Milan","Serie A",[88,66,84,85,91,94]],
  ["Gary Cahill","DEF","2015–19","England","London","Premier League",[67,58,68,60,84,89]],
  ["Willy Sagnol","DEF","2000–04","France","Munich","Bundesliga",[80,58,82,78,84,82]],
  ["Kieran Trippier","DEF","2020–24","England","Newcastle","Premier League",[72,65,88,79,82,78]],
  ["Michael Carrick","MID","2005–09","England","Manchester","Premier League",[63,71,89,79,83,81]],
  ["Ivan Rakitić","MID","2015–19","Croatia","Barcelona","La Liga",[70,82,89,85,76,82]],
  ["Blaise Matuidi","MID","2015–19","France","Paris","Ligue 1",[83,72,80,78,86,92]],
  ["Mikel Arteta","MID","2005–09","Spain","Liverpool","Premier League",[68,77,88,85,72,77]],
  ["Juninho Pernambucano","MID","2005–09","Brazil","Lyon","Ligue 1",[70,88,94,88,66,74]],
  ["Tomáš Rosický","MID","2005–09","Czechia","London","Premier League",[81,78,88,90,63,70]],
  ["Neymar","ATT","2015–19","Brazil","Barcelona","La Liga",[94,92,91,98,40,72]],
  ["Luis Suárez","ATT","2015–19","Uruguay","Barcelona","La Liga",[84,97,88,93,55,91]],
  ["Mario Mandžukić","ATT","2015–19","Croatia","Turin","Serie A",[72,87,76,75,62,96]],
  ["Dimitar Berbatov","ATT","2005–09","Bulgaria","Manchester","Premier League",[72,90,86,91,42,82]],
  ["Kevin Gameiro","ATT","2015–19","France","Madrid","La Liga",[86,84,75,82,43,77]],
  ["Luca Toni","ATT","2005–09","Italy","Munich","Bundesliga",[60,91,72,69,44,95]],
  ["Pedro","ATT","2010–14","Spain","Barcelona","La Liga",[88,86,84,89,55,78]],
  ["Dirk Kuyt","ATT","2005–09","Netherlands","Liverpool","Premier League",[78,82,78,76,68,95]],
];
const TIMELESS=new Set(["Lionel Messi","Cristiano Ronaldo"]);
function inferTags(name:string,pos:Pos,attrs:number[]){const tags:string[]=[];if(attrs[0]>=90)tags.push("PACE ABUSER");if(attrs[1]>=90)tags.push(pos==="ATT"?"POACHER":"GOAL THREAT");if(attrs[2]>=90)tags.push("CREATIVE PASSER");if(attrs[3]>=94)tags.push("PRESS RESISTANT");if(attrs[4]>=90)tags.push(pos==="GK"?"SHOT STOPPER":"DEFENSIVE WALL");if(attrs[5]>=92)tags.push("PHYSICAL FORCE");if(name==="Lionel Messi"||name==="Cristiano Ronaldo")tags.unshift("ERA PROOF");return tags.slice(0,3)}
const PLAYERS:Player[] = raw.map(([name,pos,era,nation,club,league,attrs],i)=>({id:`p${i}`,name,pos,era,nation,club,league,attrs,color:COLORS[i%COLORS.length],tags:inferTags(name,pos,attrs),timeless:TIMELESS.has(name)}));
const FORMATIONS = [
  {name:"4-3-3",slots:["GK","RB","RCB","LCB","LB","DM","RCM","LCM","RW","ST","LW"]},
  {name:"4-2-3-1",slots:["GK","RB","RCB","LCB","LB","RDM","LDM","RAM","CAM","LAM","ST"]},
  {name:"3-4-3",slots:["GK","RCB","CB","LCB","RM","RCM","LCM","LM","RW","ST","LW"]},
  {name:"4-4-2",slots:["GK","RB","RCB","LCB","LB","RM","RCM","LCM","LM","RST","LST"]},
  {name:"3-5-2",slots:["GK","RCB","CB","LCB","RWB","RDM","CAM","LDM","LWB","RST","LST"]},
];
const PERFECT_SLOTS = ["Goalkeeper","Defender","Midfielder","Attacker","Wildcard"];
const leagues = ["Premier League","La Liga","Serie A","Bundesliga","Ligue 1"];
const LEAGUE_CLUBS:Record<string,string[]>={"Premier League":["Manchester City","Arsenal","Liverpool","Chelsea","Newcastle"],"La Liga":["Real Madrid","Barcelona","Atlético","Villarreal","Sevilla"],"Serie A":["Inter","Milan","Napoli","Juventus","Atalanta"],"Bundesliga":["Bayern","Leverkusen","Dortmund","Leipzig","Frankfurt"],"Ligue 1":["Paris","Marseille","Monaco","Lyon","Lille"]};
const ERAS = [
  {id:"80s",label:"THE 80s",years:"1980–89",title:"Steel & freedom",copy:"Physical duels, direct attacks and fearless individual expression.",traits:["PHYSICAL","DIRECT","INDIVIDUAL"]},
  {id:"90s",label:"THE 90s",years:"1990–99",title:"Artists & enforcers",copy:"Technical number 10s, ruthless defenders and contrasting identities.",traits:["TECHNIQUE","DUELS","CREATIVITY"]},
  {id:"00s",label:"THE 00s",years:"2000–09",title:"Systems collide",copy:"Long-ball power met the first great waves of positional possession.",traits:["TRANSITIONS","TIKI-TAKA","POWER"]},
  {id:"10s",label:"THE 10s",years:"2010–19",title:"Press & possess",copy:"High pressing, dominant possession and the age of superteams.",traits:["PRESSING","POSSESSION","WIDTH"]},
  {id:"20s",label:"THE 20s",years:"2020–NOW",title:"The laboratory",copy:"Data-led recruitment, strict structures and positionless football.",traits:["STRUCTURE","ATHLETICISM","HYBRIDS"]},
];
const COACHES:Coach[]=[
  {name:"José Mourinho",era:"2004–15",attack:"B",defence:"S",pressing:"A",tag:"DEFENSIVE GURU",attackMod:-.02,defenceMod:.09,cleanSheetMod:.18,quote:"Control the space, control the result."},
  {name:"Pep Guardiola",era:"2008–NOW",attack:"S",defence:"A",pressing:"S",tag:"POSITIONAL MASTER",attackMod:.09,defenceMod:.04,cleanSheetMod:.08,quote:"The ball is the first defender."},
  {name:"Sir Alex Ferguson",era:"1986–13",attack:"S",defence:"A",pressing:"A",tag:"SERIAL WINNER",attackMod:.08,defenceMod:.04,cleanSheetMod:.06,quote:"Win the moment after the 90th minute."},
  {name:"Carlo Ancelotti",era:"1995–NOW",attack:"A",defence:"A",pressing:"B",tag:"PLAYER WHISPERER",attackMod:.05,defenceMod:.05,cleanSheetMod:.07,quote:"Give great players the space to solve games."},
  {name:"Jürgen Klopp",era:"2008–24",attack:"S",defence:"B",pressing:"S",tag:"PRESSING ENGINE",attackMod:.1,defenceMod:.01,cleanSheetMod:.02,quote:"Turn chaos into the best playmaker."},
  {name:"Diego Simeone",era:"2011–NOW",attack:"C",defence:"S",pressing:"A",tag:"SIEGE ARCHITECT",attackMod:-.04,defenceMod:.11,cleanSheetMod:.2,quote:"Suffer together, strike together."},
];
const SEASONS:Record<string,LeagueSeason[]>={
  "80s":[{league:"Serie A",year:1988,powerhouses:["Inter","Milan","Napoli","Juventus","Roma"],story:"Maradona's Napoli and the great Milan machine define the hardest league in Europe."},{league:"English First Division",year:1986,powerhouses:["Liverpool","Everton","Arsenal","Manchester United","Tottenham"],story:"Merseyside rules a direct, unforgiving English landscape."}],
  "90s":[{league:"Serie A",year:1998,powerhouses:["Juventus","Inter","Lazio","Milan","Parma"],story:"Italian football is a weekly tactical examination with no soft fixtures."},{league:"Premier League",year:1999,powerhouses:["Manchester United","Arsenal","Chelsea","Leeds","Liverpool"],story:"United chase history while Wenger's Arsenal modernise England."}],
  "00s":[{league:"La Liga",year:2006,powerhouses:["Barcelona","Real Madrid","Valencia","Sevilla","Villarreal"],story:"Ronaldinho's Barcelona meets Madrid's stars and Valencia's structure."},{league:"Premier League",year:2005,powerhouses:["Chelsea","Manchester United","Arsenal","Liverpool","Tottenham"],story:"Chelsea set a defensive standard while the old powers regroup."}],
  "10s":[{league:"Premier League",year:2015,powerhouses:["Chelsea","Manchester City","Arsenal","Manchester United","Liverpool"],story:"Chelsea are the benchmark; City are loaded, while Liverpool remain unfinished."},{league:"La Liga",year:2017,powerhouses:["Real Madrid","Barcelona","Atlético","Sevilla","Villarreal"],story:"The Clásico giants are at full force and Atlético make every point hurt."}],
  "20s":[{league:"Premier League",year:2024,powerhouses:["Manchester City","Arsenal","Liverpool","Chelsea","Newcastle"],story:"City's machine meets Arsenal's rise and a league built on pressing data."},{league:"Bundesliga",year:2024,powerhouses:["Leverkusen","Bayern","Dortmund","Leipzig","Stuttgart"],story:"Leverkusen break the old order while Bayern chase from unfamiliar ground."}],
};

function hash(s:string){let h=2166136261; for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)} return h>>>0}
function rng(seed:string){let x=hash(seed)||1; return ()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
function sample<T>(items:T[], n:number, seed:string){const pool=[...items],r=rng(seed),out:T[]=[];while(pool.length&&out.length<n)out.push(pool.splice(Math.floor(r()*pool.length),1)[0]);return out}
function balancedPlayers(items:Player[],seed:string){const r=rng(seed),pool=[...items],chosen:Player[]=[];while(chosen.length<3&&pool.length){const weights=pool.map(p=>{const rating=overall(p);return rating>=95?.12:rating>=90?.32:rating>=84?.8:1.45}),total=weights.reduce((a,b)=>a+b,0);let roll=r()*total,index=0;for(;index<weights.length-1;index++){roll-=weights[index];if(roll<=0)break}chosen.push(pool.splice(index,1)[0])}return chosen}
const PEAK_RATINGS:Record<string,number>={"Lionel Messi|2010–14":101,"Lionel Messi|2005–09":94,"Cristiano Ronaldo|2010–14":99,"Cristiano Ronaldo|2005–09":95,"Sergio Ramos|2010–14":96,"Sergio Ramos|2005–09":88,"Ronaldo Nazário|1995–99":99,"Zinedine Zidane|2000–04":98,"Thierry Henry|2000–04":98,"Ronaldinho|2005–09":98,"Paolo Maldini|1990–94":98,"Xavi|2005–09":97,"Andrés Iniesta|2010–14":97,"Manuel Neuer|2010–14":97};
function overall(p:Player){
  if(PEAK_RATINGS[`${p.name}|${p.era}`]) return PEAK_RATINGS[`${p.name}|${p.era}`];
  const weights=p.pos==="ATT"?[.18,.25,.18,.24,.01,.14]:p.pos==="MID"?[.12,.12,.25,.21,.15,.15]:p.pos==="DEF"?[.13,.04,.14,.1,.34,.25]:[.06,.01,.2,.08,.4,.25];
  return Math.round(p.attrs.reduce((sum,value,index)=>sum+value*weights[index],0));
}
function playerDecade(p:Player){
  if(p.name==="Franz Beckenbauer") return 70;
  const year=Number(p.era.match(/\d{4}/)?.[0]||2000);
  return Math.floor(year/10)*10%100;
}
function eraFit(p:Player,eraId:string){
  if(p.timeless)return 100;
  const target=Number(eraId.slice(0,2));
  const distance=Math.abs(playerDecade(p)-target)/10;
  const base=distance===0?100:distance===1?91:distance===2?83:distance===3?77:72;
  const styleBonus=eraId==="80s"?p.attrs[5]>90?2:0:eraId==="90s"?p.attrs[3]>90?2:0:eraId==="00s"?p.attrs[2]>90?2:0:eraId==="10s"?p.attrs[0]>90?2:0:p.attrs[2]>90?2:0;
  return Math.min(100,base+styleBonus);
}
function squadTagBonus(picks:Pick[],coach?:Coach){const tags=picks.flatMap(p=>p.tags),names=new Set(picks.map(p=>p.name));let bonus=0;const activated:string[]=[];if(names.has("Lionel Messi")&&names.has("Neymar")&&names.has("Luis Suárez")){bonus+=4;activated.push("MSN TRIO")}if(coach?.attack==="S"&&tags.filter(t=>t==="CREATIVE PASSER").length>=2){bonus+=2;activated.push("CREATOR'S SYSTEM")}if(coach?.pressing==="S"&&tags.filter(t=>t==="PRESS RESISTANT"||t==="PHYSICAL FORCE").length>=3){bonus+=2;activated.push("PRESS-PROOF XI")}if(coach?.defence==="S"&&tags.filter(t=>t==="DEFENSIVE WALL"||t==="SHOT STOPPER").length>=2){bonus+=2;activated.push("FORTRESS UNIT")}return {bonus,activated}}
function dailySeed(){return new Date().toISOString().slice(0,10)}
function grade(score:number){return score>=95?"IMMORTAL":score>=88?"WORLD CLASS":score>=80?"CONTENDER":score>=70?"DANGEROUS":"CULT HEROES"}

function simulate(game:Game,picks:Pick[],seed:string,league:string,position:Pos,eraId="",coach?:Coach,season?:LeagueSeason):Result{
  const r=rng(seed+picks.map(p=>p.id+(p.value||"")).join(""));
  if(game==="era"){
    const avg=picks.reduce((s,p)=>s+overall(p),0)/picks.length;
    const nations=new Set(picks.map(p=>p.nation)).size, clubs=new Set(picks.map(p=>p.club)).size,fit=eraId?Math.round(picks.reduce((s,p)=>s+eraFit(p,eraId),0)/picks.length):90;
    const chemistry=Math.max(60,Math.round(98-nations*2-clubs+avg/7)),tagLink=squadTagBonus(picks,coach); const score=Math.min(101,Math.round(avg*.62+chemistry*.2+fit*.18+tagLink.bonus));
    const games=season?.league==="Bundesliga"?34:38,rivals=season?.powerhouses||LEAGUE_CLUBS[league],matches:MatchResult[]=[];let wins=0,draws=0,losses=0,cleanSheets=0,goalsFor=0,goalsAgainst=0;
    const strength=(score-72)/28,attackBoost=coach?.attackMod||0,defenceBoost=coach?.defenceMod||0;
    for(let i=0;i<games;i++){const opponent=rivals[i%rivals.length],roll=r(),winLine=.53+strength*.27+attackBoost+defenceBoost*.35,drawLine=.77+strength*.08+defenceBoost*.4;let result:"W"|"D"|"L",gf:number,ga:number;
      if(roll<winLine){result="W";wins++;gf=1+Math.floor(r()*3+(attackBoost>0?1:0));ga=r()<.34+(coach?.cleanSheetMod||0)?0:Math.floor(r()*2)}else if(roll<drawLine){result="D";draws++;gf=Math.floor(r()*2);ga=gf}else{result="L";losses++;gf=Math.floor(r()*2);ga=1+Math.floor(r()*2)}
      if(ga===0)cleanSheets++;goalsFor+=gf;goalsAgainst+=ga;const tone=ga===0?"LOCKDOWN":gf>=3?"STATEMENT":result==="L"?"PUNISHED":result==="D"?"STALEMATE":"CONTROLLED";const summary=ga===0?`${coach?.name||"The manager"}'s structure protected the box and killed the final pass.`:gf>=3?"The attack stretched the game early and never released its grip.":result==="L"?"One transition exposed the risk and the comeback arrived too late.":result==="D"?"Possession came easily; the decisive action never did.":"The XI managed the key moments without needing to dominate every phase.";matches.push({result,score:`${gf}-${ga}`,opponent,summary,tone})}
    const pts=wins*3+draws,gd=goalsFor-goalsAgainst,best=[...picks].sort((a,b)=>overall(b)-overall(a))[0],keeper=picks.find(p=>p.pos==="GK")||picks[0];
    const table:TableRow[]=[{club:"Era XI",played:games,wins,draws,losses,gf:goalsFor,ga:goalsAgainst,gd,points:pts,highlight:true},...rivals.map((club,i)=>{const points=Math.max(48,Math.min(games*3,Math.round((games===34?76:91)-i*5+r()*9)));const rw=Math.min(games,Math.floor(points/3));const rd=Math.min(games-rw,points-rw*3);const rl=games-rw-rd;const rgf=Math.round(47+points*.38+r()*12),rga=Math.round(34+i*5+r()*16);return {club,played:games,wins:rw,draws:rd,losses:rl,gf:rgf,ga:rga,gd:rgf-rga,points}})].sort((a,b)=>b.points-a.points||b.gd-a.gd);
    const awards=[table[0].highlight?`${coach?.name} · Manager of the Year`:`${coach?.name} · Tactical Award`,`${best.name} · Player of the Year`,cleanSheets>=15?`${keeper.name} · Golden Glove (${cleanSheets})`:`${best.name} · Team MVP`,table[0].highlight?`${season?.league||league} Champions · ${season?.year||"ALT"}`:"European Qualification"];
    const review=[{label:"IDENTITY",value:coach?.tag||"BALANCED",copy:`The team reflected ${coach?.name||"the coach"}: ${cleanSheets} clean sheets and ${goalsFor} goals.`},{label:"TIME TRAVEL",value:`${fit}% FIT`,copy:`${eraId.toUpperCase()} football rewarded ${fit>90?"a squad built for its demands":"adaptable stars more than perfect natives"}.`},{label:"VERDICT",value:table[0].highlight?"ERA-DEFINING":"NEARLY GREAT",copy:table[0].highlight?"This XI would change the history of the league.":`The side finished ${table.findIndex(t=>t.highlight)+1}${table.findIndex(t=>t.highlight)===1?"nd":"th"}, with one structural weakness left exposed.`}];
    return {title:table[0].highlight?`${season?.year} champions. History rewritten.`:`${pts} points in ${season?.year}. The era fought back.`,score,grade:grade(score),story:`${coach?.name} took this XI into ${season?.league}. ${season?.story}`,stats:[{label:"Record",value:`${wins}-${draws}-${losses}`},{label:"Era fit",value:`${fit}%`},{label:"Clean sheets",value:String(cleanSheets)},{label:"Position",value:`#${table.findIndex(t=>t.highlight)+1}`}],badges:[table[0].highlight?"League champions":"Title race",cleanSheets>=15?"Iron curtain":"Front-foot risk",...(tagLink.activated.length?tagLink.activated:[gd>55?"Goal machine":"Fine margins"])],detail:[`${coach?.tag} produced ${cleanSheets} clean sheets.`,tagLink.activated.length?`${tagLink.activated.join(" + ")} added ${tagLink.bonus} chemistry points.`:`The player profiles created no special tactical link.`,`${best.name} was named player of the season.`,`${goalsFor} scored, ${goalsAgainst} conceded, ${gd>=0?"+":""}${gd} goal difference.`],matches,table,awards,review};
  }
  if(game==="perfect"){
    const avg=picks.reduce((s,p)=>s+overall(p),0)/picks.length;const games=20;const strength=(avg-72)/25;
    let w=0,d=0,l=0;const moments:string[]=[],matches:MatchResult[]=[];const rivals=LEAGUE_CLUBS[league];for(let i=1;i<=games;i++){const roll=r(),opponent=rivals[i%rivals.length];if(roll<.62+strength*.25){w++;const score=`${3+Math.floor(r()*4)}-${Math.floor(r()*3)}`;matches.push({result:"W",score,opponent,summary:"Quick combinations and constant rotations overwhelmed the smaller pitch.",tone:"FLUID FIVE"})}else if(roll<.84+strength*.1){d++;const score=r()>.5?"3-3":"2-2";matches.push({result:"D",score,opponent,summary:"The press created chances at both ends, but neither side controlled the final minute.",tone:"END TO END"});if(moments.length<3)moments.push(`Round ${i} · A frantic draw stopped the streak.`)}else{l++;const score=`${1+Math.floor(r()*3)}-${4+Math.floor(r()*3)}`;matches.push({result:"L",score,opponent,summary:"One weak defensive rotation was targeted again and again.",tone:"EXPOSED"});if(moments.length<3)moments.push(`Round ${i} · The five were pulled out of shape.`)}}
    const pts=w*3+d,score=Math.min(99,Math.round(68+(w/games)*30+(l===0?3:0)));if(!moments.length)moments.push("Every challenger arrived. Every challenger left beaten.");
    const yourClub="Arcade Five";const competitorPoints=[pts,...rivals.map((_,i)=>Math.max(24,Math.min(games*3,Math.round(48-i*4+r()*6))))];const table:TableRow[]=[{club:yourClub,played:games,wins:w,draws:d,losses:l,gf:w*5+d*3+l*2,ga:w*2+d*3+l*5,gd:w*3-l*3,points:pts,highlight:true},...rivals.map((x,i)=>{const points=competitorPoints[i+1],rw=Math.floor(points/3),rd=Math.min(games-rw,points-rw*3),rl=games-rw-rd,gf=rw*4+rd*3+rl*2,ga=rw*2+rd*3+rl*5;return {club:`${x} Five`,played:games,wins:rw,draws:rd,losses:rl,gf,ga,gd:gf-ga,points}})].sort((a,b)=>b.points-a.points||b.gd-a.gd);
    const star=[...picks].sort((a,b)=>overall(b)-overall(a))[0];const awards=[w/games>.72?"Five-a-Side Coach of the Tour":"Tactical Innovator",`${star.name} · Tournament MVP`,`${star.name} · ${Math.round(22+r()*18)} tour goals`,l===0?"Golden Five Trophy":"Finals Qualification"];
    const review=[{label:"CHEMISTRY",value:avg>89?"TELEPATHIC":"VOLATILE",copy:"Five-a-side magnified every first touch, rotation and recovery run."},{label:"DECISIVE PLAYER",value:star.name,copy:`The highest-rated player became the release valve under pressure.`},{label:"VERDICT",value:table[0].highlight?"TOUR WINNERS":"BOX-OFFICE",copy:table[0].highlight?"The five mastered space at both ends.":"Spectacular with the ball, but one role still lacked balance."}];
    return {title:l===0&&d===0?"PERFECT FIVE. Every round won.":l===0?"Invincible on the small pitch.":`${w} wins on the world tour.`,score,grade:grade(score),story:`Five players, no hiding places. Your ${league} selection entered a 20-round small-sided gauntlet.`,stats:[{label:"Record",value:`${w}-${d}-${l}`},{label:"Points",value:String(pts)},{label:"Tour position",value:`#${table.findIndex(t=>t.highlight)+1}`},{label:"Win rate",value:`${Math.round(w/games*100)}%`}],badges:[l===0?"Invincible Five":"Box office",w/games>.8?"Rotation masters":"Transition threat",avg>90?"Elite chemistry":"Beautiful chaos"],detail:moments,matches,table,awards,review};
  }
  const vals=picks.map(p=>p.value||70), weights=position==="ATT"?[.18,.27,.16,.2,.04,.15]:position==="MID"?[.13,.1,.27,.22,.13,.15]:position==="DEF"?[.14,.04,.16,.12,.31,.23]:[.09,.03,.2,.08,.36,.24];
  const ov=Math.round(vals.reduce((s,v,i)=>s+v*weights[i],0));const apps=Math.round(29+r()*9),goals=position==="ATT"?Math.round((ov-65)*.7+r()*8):position==="MID"?Math.round((ov-68)*.28+r()*5):Math.round(r()*4),assists=Math.round((vals[2]-60)*.25+r()*5),score=Math.min(99,ov+Math.round(r()*5));
  const top=A[vals.indexOf(Math.max(...vals))], low=A[vals.indexOf(Math.min(...vals))];
  return {title:`A ${score}-rated breakout season.`,score,grade:grade(score),story:`Built around elite ${top.toLowerCase()}, your creation played with a clear identity — and opponents noticed.`,stats:[{label:"Appearances",value:String(apps)},{label:"Goals",value:String(goals)},{label:"Assists",value:String(assists)},{label:"Avg. rating",value:(6.4+(score-65)/20).toFixed(2)}],badges:[score>91?"Player of the year":"Breakout star",goals>20?"Golden boot":"Fan favourite",`€${Math.max(18,(score-62)*5)}m value`],detail:[`${top} became the signature weapon.`,`${low} remained the clearest weakness.`,score>88?"The season ended with silverware and individual honours.":"A strong first season left room for a defining second act."]};
}

function Mark(){return <span className="mark" aria-hidden="true"><i></i><i></i><i></i></span>}
function Header({go}: {go:(m:Mode)=>void}){return <header><button className="brand" onClick={()=>go("home")}><Mark/> FOOTBALL <b>ARCADE</b></button><nav><button onClick={()=>go("home")}>GAMES</button><button onClick={()=>go("about")}>THE MODEL</button></nav><span className="live"><i/> DAILY LIVE</span></header>}
function Home({go}:{go:(m:Mode)=>void}){const games:[Game,string,string,string][]=[["era","01","ERA XI","Build an impossible XI, roll a manager, then rewrite a historic season."],["perfect","02","FIVE-A-SIDE","Five players. Tiny pitch. No place to hide."],["player","03","BUILD A PLAYER","Steal six elite attributes. Simulate the season."]];return <main className="home"><section className="hero"><div className="eyebrow">THREE GAMES · INFINITE IMPOSSIBILITIES</div><h1>FOOTBALL,<br/><em>REWRITTEN.</em></h1><p>Draft icons. Break the simulation. Share the proof.</p><button className="primary" onClick={()=>go("era")}>PLAY TODAY’S ERA XI <span>↗</span></button><div className="scroll">SCROLL TO CHOOSE <b>↓</b></div></section><section className="game-grid">{games.map(([id,num,title,copy])=><button key={id} className={`game-tile ${id}`} onClick={()=>go(id)}><span className="num">{num}</span><span className="mini-mark"><Mark/></span><h2>{title}</h2><p>{copy}</p><span className="play">PLAY NOW <b>↗</b></span></button>)}</section><section className="proof"><span>NO LOGIN</span><span>3–5 MINUTES</span><span>NEW DAILY SEED</span><span>SHAREABLE RESULTS</span></section></main>}
function Card({p,onPick,attribute,eraId,spinning}:{p:Pick;onPick?:()=>void;attribute?:string;eraId?:string;spinning?:boolean}){const val=attribute? p.attrs[A.indexOf(attribute)]:overall(p);return <button className={`player-card ${spinning?"spinning":""}`} onClick={onPick} disabled={!onPick||spinning} style={{"--accent":p.color} as React.CSSProperties}><div className="card-top"><span>{attribute||`${p.pos} · PEAK`}</span><b>{val}</b></div><div className="portrait"><span>{spinning?"?":p.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span></div><div className="card-copy"><small>{p.era} · {p.nation}</small><h3>{spinning?"SEARCHING…":p.name}</h3><p>{p.club} · {p.league}</p>{eraId&&<div className="era-fit"><span>ERA FIT</span><b>{eraFit(p,eraId)}%</b></div>}<div className="player-tags">{p.tags.map(tag=><i key={tag}>{tag}</i>)}</div></div>{attribute?<div className="attr-line"><strong>{attribute}</strong><span style={{width:`${Math.min(100,val)}%`}}/></div>:<div className="attribute-grid">{A.map((a,i)=><span key={a}><b>{p.attrs[i]}</b>{a}</span>)}</div>}</button>}
function slotPosition(slot:string):Pos {if(slot==="GK")return "GK";if(/WB|M/.test(slot))return "MID";if(/B$|CB/.test(slot))return "DEF";return "ATT"}
function Pitch({slots,picks,current,onSwap}:{slots:string[];picks:Pick[];current:number;onSwap?:(from:number,to:number)=>void}){return <div className="pitch"><div className="pitch-circle"/><div className="pitch-box top"/><div className="pitch-box bottom"/><div className="pitch-team">{(["ATT","MID","DEF","GK"] as Pos[]).map(line=><div className={`pitch-line line-${line.toLowerCase()}`} key={line}>{slots.map((slot,index)=>({slot,index})).filter(item=>slotPosition(item.slot)===line).map(({slot,index})=>{const picked=picks[index];return <div draggable={Boolean(picked&&onSwap)} onDragStart={e=>e.dataTransfer.setData("text/plain",String(index))} onDragOver={e=>onSwap&&e.preventDefault()} onDrop={e=>{e.preventDefault();onSwap?.(Number(e.dataTransfer.getData("text/plain")),index)}} className={`pitch-slot ${index===current?"active":""} ${picked?"filled":""}`} key={`${slot}-${index}`}><span>{picked?overall(picked):"+"}</span><b>{picked?picked.name:slot}</b>{picked&&<small>{picked.era} · DRAG TO MOVE</small>}</div>})}</div>)}</div></div>}
function EraSetupPanel({slots,picks,onSwap,coach,season,pendingSeason,spinning}:{slots:string[];picks:Pick[];onSwap:(a:number,b:number)=>void;coach:Coach|null;season:LeagueSeason|null;pendingSeason:LeagueSeason|null;spinning:"coach"|"league"|"year"|null}){return <div className="era-final-setup"><div className="final-pitch"><Pitch slots={slots} picks={picks} current={-1} onSwap={onSwap}/></div><div className="final-rolls"><section className={`roll-card ${spinning==="coach"?"rolling":""}`}><span>STEP 04 · MANAGER</span>{coach?<><div className="coach-name"><i>{coach.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</i><div><h3>{coach.name}</h3><b>{coach.tag}</b></div></div><div className="coach-stats"><span>ATTACK <b>{coach.attack}</b></span><span>DEFENCE <b>{coach.defence}</b></span><span>PRESSING <b>{coach.pressing}</b></span></div><p>“{coach.quote}”</p></>:<div className="roll-placeholder">{spinning==="coach"?<div className="reveal-reel">{COACHES.slice(0,5).map(c=><b key={c.name}>{c.name}<small>{c.tag}</small></b>)}</div>:<><i className="reveal-icon">?</i><b>THE DUGOUT AWAITS</b><small>One tactical identity will reshape your XI</small></>}</div>}</section><section className={`roll-card ${spinning==="league"||spinning==="year"?"rolling":""}`}><span>STEP 05 · DESTINATION</span>{season?<><h3>{season.league} · {season.year}</h3><b className="season-tag">HISTORICAL POWER INDEX</b><p>{season.story}</p><div className="powerhouse-list">{season.powerhouses.map((club,i)=><span key={club}><b>{i+1}</b>{club}</span>)}</div></>:<div className="roll-placeholder">{spinning==="league"?<div className="reveal-reel league-reel">{Array.from(new Set(Object.values(SEASONS).flat().map(item=>item.league))).map(item=><b key={item}>{item}<small>SELECTING THE LEAGUE</small></b>)}</div>:spinning==="year"?<div className="reveal-reel year-reel">{[(pendingSeason?.year||2000)-2,(pendingSeason?.year||2000)-1,pendingSeason?.year||2000,(pendingSeason?.year||2000)+1].map((year,i)=><b key={`${year}-${i}`}>{year}<small>{pendingSeason?.league} ? ERA-VALID SEASON</small></b>)}</div>:<><i className="reveal-icon">?</i><b>HISTORY IS UNWRITTEN</b><small>Your era decides the possible destinations</small></>}</div>}</section></div></div>}
function SeasonReplay({matches,table,onComplete,onReset}:{matches:MatchResult[];table:TableRow[];onComplete:()=>void;onReset:()=>void}){
  const [day,setDay]=useState(1),[playing,setPlaying]=useState(true);
  useEffect(()=>{if(!playing||day>=matches.length)return;const timer=setTimeout(()=>setDay(d=>Math.min(matches.length,d+1)),220);return()=>clearTimeout(timer)},[day,playing,matches.length]);
  useEffect(()=>{if(day!==matches.length)return;const timer=setTimeout(onComplete,350);return()=>clearTimeout(timer)},[day,matches.length,onComplete]);
  const played=matches.slice(0,day),wins=played.filter(m=>m.result==="W").length,draws=played.filter(m=>m.result==="D").length,losses=day-wins-draws,points=wins*3+draws;
  const live=table.map(row=>row.highlight?{...row,played:day,wins,draws,losses,points}:{...row,played:day,wins:Math.round(row.wins*day/matches.length),draws:Math.round(row.draws*day/matches.length),losses:Math.round(row.losses*day/matches.length),points:Math.round(row.points*day/matches.length)}).sort((a,b)=>b.points-a.points||b.gd-a.gd);
  const place=live.findIndex(r=>r.highlight)+1,leader=live[0],gap=leader.highlight?Math.max(0,leader.points-(live[1]?.points||0)):leader.points-points;
  const status=day===matches.length?(place===1?"CHAMPIONS":"SEASON COMPLETE"):place===1?(gap>0?`${gap} PTS CLEAR`:"TOP ON GOAL DIFFERENCE"):`${gap} PTS OFF THE LEAD`;
  return <section className="season-replay"><div className="replay-head"><div><span>LIVE SEASON REPLAY</span><h3>MATCHDAY {String(day).padStart(2,"0")} <i>/ {matches.length}</i></h3></div><div className="race-status"><small>TITLE RACE</small><b>{status}</b></div><button onClick={()=>{if(day===matches.length){onReset();setDay(1);setPlaying(true)}else setPlaying(v=>!v)}}>{day===matches.length?"↻ REPLAY":playing?"Ⅱ PAUSE":"▶ CONTINUE"}</button></div><div className="replay-stage"><div><div className="current-match"><span className={matches[day-1].result.toLowerCase()}>{matches[day-1].result}</span><div><small>MD {day} · {matches[day-1].tone}</small><h4>ERA XI <b>{matches[day-1].score}</b> {matches[day-1].opponent}</h4><p>{matches[day-1].summary}</p></div></div><div className="match-dots">{matches.map((m,i)=><button onClick={()=>{setDay(i+1);setPlaying(false);if(i+1===matches.length)onComplete()}} className={`${m.result.toLowerCase()} ${i+1===day?"selected":""} ${i>=day?"future":""}`} aria-label={`Match ${i+1}, ${m.opponent}, ${m.score}`} key={i}><span>{i<day?m.result:i+1===day?m.result:i+1}</span></button>)}</div></div><div className="live-table"><div><span>LIVE TABLE</span><small>AFTER MD {day}</small></div>{live.slice(0,6).map((row,i)=><div className={row.highlight?"you":""} key={row.club}><b>{i+1}</b><span>{row.club}</span><small>{row.played}</small><strong>{row.points}</strong></div>)}</div></div></section>
}
function TeamReview({review}:{review:NonNullable<Result["review"]>}){return <section className="team-review"><div className="result-section-title"><span>THE REVIEW</span><small>How the pieces worked together</small></div><div>{review.map(item=><article key={item.label}><span>{item.label}</span><h3>{item.value}</h3><p>{item.copy}</p></article>)}</div></section>}
function GameView({game,go}:{game:Game;go:(m:Mode)=>void}){
  const [daily,setDaily]=useState(true),[nonce,setNonce]=useState(0),[picks,setPicks]=useState<Pick[]>([]),[result,setResult]=useState<Result|null>(null),[league,setLeague]=useState(leagues[0]),[position,setPosition]=useState<Pos>("ATT"),[formation,setFormation]=useState<typeof FORMATIONS[number]|null>(null),[selectedEra,setSelectedEra]=useState(""),[rerollUsed,setRerollUsed]=useState(false),[rerollNonce,setRerollNonce]=useState(0),[spinning,setSpinning]=useState(false),[coach,setCoach]=useState<Coach|null>(null),[season,setSeason]=useState<LeagueSeason|null>(null),[phaseSpin,setPhaseSpin]=useState<"coach"|"league"|"year"|null>(null),[pendingSeason,setPendingSeason]=useState<LeagueSeason|null>(null),[revealFinal,setRevealFinal]=useState(true);
  const seed=`${daily?dailySeed():"random-run"}-${game}-${nonce}-${league}-${position}-${selectedEra}`;
  const formationChoices=useMemo(()=>sample(FORMATIONS,3,seed+"formations"),[seed]);
  const slots=game==="era"?(formation?.slots||[]):game==="perfect"?PERFECT_SLOTS:A; const round=picks.length;const done=slots.length>0&&round>=slots.length;
  const needed:Pos|undefined=game==="era"?(slots[round]?slotPosition(slots[round]):undefined):game==="perfect"?(round===0?"GK":round===1?"DEF":round===2?"MID":round===3?"ATT":undefined):undefined;
  const options=useMemo(()=>{const available=PLAYERS.filter(p=>(!needed||p.pos===needed)&&!picks.some(x=>x.name===p.name));const chosen=game==="player"?sample(available,3,seed+round+rerollNonce):balancedPlayers(available,seed+round+rerollNonce);return chosen.map(p=>game==="player"?{...p,attribute:A[round],value:p.attrs[round]}:p)},[round,seed,needed,game,picks,rerollNonce]);
  function resetForChoice(){setPicks([]);setResult(null);setFormation(null);setSelectedEra("");setRerollUsed(false);setRerollNonce(0);setCoach(null);setSeason(null);setPendingSeason(null);setRevealFinal(true);setNonce(n=>n+1)}
  function pick(p:Pick){setPicks(x=>[...x,{...p,slot:slots[round]}])}
  function run(){const res=simulate(game,picks,seed,league,position,selectedEra,coach||undefined,season||undefined);setRevealFinal(!res.matches);setResult(res);setTimeout(()=>document.querySelector(".result")?.scrollIntoView({behavior:"smooth",block:"start"}),80);try{localStorage.setItem("football-arcade-last",JSON.stringify({game,picks,seed,league,position,res}))}catch{}}
  function restart(){setPicks([]);setResult(null);setFormation(null);setSelectedEra("");setRerollUsed(false);setRerollNonce(0);setCoach(null);setSeason(null);setPendingSeason(null);setRevealFinal(true);setNonce(n=>n+1)}
  function reroll(){if(rerollUsed)return;setSpinning(true);setRerollUsed(true);setTimeout(()=>{setRerollNonce(n=>n+1);setSpinning(false)},700)}
  function swapPlayers(from:number,to:number){if(from===to||!picks[from]||!picks[to])return;const fromRole=slotPosition(slots[from]),toRole=slotPosition(slots[to]);if(picks[from].pos!==toRole||picks[to].pos!==fromRole)return;setPicks(current=>{const next=[...current];[next[from],next[to]]=[next[to],next[from]];return next})}
  function rollCoach(){setPhaseSpin("coach");setTimeout(()=>{setCoach(sample(COACHES,1,seed+"coach")[0]);setPhaseSpin(null)},1700)}
  function rollSeason(){const rolled=sample(SEASONS[selectedEra],1,seed+"season")[0];setPendingSeason(rolled);setPhaseSpin("league");setTimeout(()=>{setLeague(rolled.league);setPhaseSpin("year");setTimeout(()=>{setSeason(rolled);setPhaseSpin(null)},1700)},1700)}
  async function share(){const url=new URL(location.href);url.searchParams.set("result",btoa(unescape(encodeURIComponent(JSON.stringify({game,result,picks:picks.map(p=>p.name)})))));history.replaceState({},"",url);const data={title:result?.title,text:`I scored ${result?.score} in ${game==="era"?"Era XI":game==="perfect"?"Perfect Season":"Build a Player"}. Beat that.`,url:url.href};if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(url.href)}
  const title=game==="era"?"ERA XI":game==="perfect"?"FIVE-A-SIDE":"BUILD A PLAYER"; const copy=game==="era"?"Eleven picks. One manager. A historic league rewritten.":game==="perfect"?"Draft five roles. Survive the small-sided world tour.":"Borrow six gifts. Create one superstar.";
  return <main className="game-page"><section className="game-head"><button className="back" onClick={()=>go("home")}>← ALL GAMES</button><div><span>FOOTBALL ARCADE / {game.toUpperCase()}</span><h1>{title}</h1><p>{copy}</p></div><button className={`daily-toggle ${daily?"on":""}`} onClick={()=>{setDaily(v=>!v);resetForChoice()}}><i/> {daily?"DAILY CHALLENGE":"RANDOM RUN"}</button></section>
  {game==="era"&&!selectedEra&&!result&&<section className="era-select"><span className="section-label">STEP 01 · CHOOSE THE WORLD</span><h2>WHAT KIND OF<br/>FOOTBALL WINS?</h2><div className="era-options">{ERAS.map(era=><button key={era.id} onClick={()=>setSelectedEra(era.id)}><span>{era.years}</span><strong>{era.label}</strong><h3>{era.title}</h3><p>{era.copy}</p><div>{era.traits.map(t=><i key={t}>{t}</i>)}</div></button>)}</div></section>}
  {game==="era"&&selectedEra&&!formation&&!result&&<section className="formation-select"><span className="section-label">STEP 02 · CHOOSE YOUR SHAPE · {ERAS.find(e=>e.id===selectedEra)?.label}</span><h2>THREE SYSTEMS.<br/>ONE WAY TO PLAY.</h2><div className="formation-options">{formationChoices.map(f=><button onClick={()=>setFormation(f)} key={f.name}><Pitch slots={f.slots} picks={[]} current={-1}/><strong>{f.name}</strong><small>{f.name==="4-3-3"?"WIDTH & CONTROL":f.name==="3-5-2"?"MIDFIELD OVERLOAD":f.name==="4-4-2"?"CLASSIC BALANCE":"TACTICAL FLEX"}</small></button>)}</div></section>}
  {game==="perfect"&&picks.length===0&&!result&&<div className="setup"><span>CHOOSE YOUR FOOTBALL IDENTITY</span>{leagues.map(l=><button className={league===l?"active":""} onClick={()=>{setLeague(l);resetForChoice()}} key={l}>{l}</button>)}</div>}
  {game==="player"&&picks.length===0&&!result&&<div className="setup"><span>YOUR POSITION</span>{(["ATT","MID","DEF","GK"] as Pos[]).map(p=><button className={position===p?"active":""} onClick={()=>{setPosition(p);resetForChoice()}} key={p}>{p}</button>)}</div>}
  {!result&&slots.length>0&&<section className={`draft ${game==="era"?"pitch-draft":""}`}><div className="progress"><span>ROUND {Math.min(round+1,slots.length)} / {slots.length}</span><div>{slots.map((s,i)=><i className={i<round?"filled":i===round?"now":""} key={`${s}-${i}`}/>)}</div><b>{done?"SQUAD COMPLETE":game==="player"?`CHOOSE ${A[round]}`:`CHOOSE YOUR ${slots[round]}`}</b></div>{game==="era"&&!done?<div className="squad-builder"><div className="pitch-wrap"><span className="section-label">{formation?.name} · {ERAS.find(e=>e.id===selectedEra)?.label} · LIVE XI</span><Pitch slots={slots} picks={picks} current={round} onSwap={swapPlayers}/></div><div className="choice-panel"><div className="choice-heading"><span className="section-label">AVAILABLE {needed}S · PICK ONE</span><button className="reroll" disabled={rerollUsed||spinning} onClick={reroll}>{rerollUsed?"REROLL USED":"↻ ONE REROLL"}</button></div><div className="cards">{options.map(p=><Card key={p.id} p={p} eraId={selectedEra} spinning={spinning} onPick={()=>pick(p)}/>)}</div><p className="draft-note">Elite, cult hero or honest pro? Every roll has a ceiling—and every era changes the fit.</p></div></div>:!done?<div className="cards">{options.map(p=><Card key={p.id} p={p} attribute={game==="player"?A[round]:undefined} onPick={()=>pick(p)}/>)}</div>:<div className="ready">{game==="era"?<div className="final-pitch"><Pitch slots={slots} picks={picks} current={-1} onSwap={swapPlayers}/></div>:<div className="picked-strip">{picks.map(p=><div key={p.slot}><span>{p.slot}</span><b>{game==="player"?p.value:overall(p)}</b><small>{p.name}</small></div>)}</div>}<h2>{game==="perfect"?"CAN THE FIVE RULE THE TOUR?":game==="era"?"YOUR XI IS READY.":"THE PLAYER IS BUILT."}</h2>{game==="era"&&<p className="swap-hint">Drag players on the pitch to swap roles before simulating.</p>}<button className="primary" onClick={run}>SIMULATE THE SEASON <span>↗</span></button></div>}</section>}
  {game==="era"&&done&&!result&&<section className="era-post-draft"><span className="section-label">SQUAD LOCKED · NOW BUILD THE WORLD</span><EraSetupPanel slots={slots} picks={picks} onSwap={swapPlayers} coach={coach} season={season} pendingSeason={pendingSeason} spinning={phaseSpin}/><div className="post-draft-action"><div className="casino-route"><span><i>1</i> MANAGER</span><b>?</b><span><i>2</i> DESTINATION</span><b>?</b><span className={coach&&season?"active":""}><i>3</i> SEASON RESULTS</span><strong>?</strong></div><h2>{!coach?"WHO LEADS THEM?":!season?"WHERE DO THEY LAND?":"LET HISTORY DECIDE."}</h2><p>{!coach?"Roll one manager. Their tactical identity will change the season model.":!season?"Your chosen era determines which historical leagues can appear.":`${coach.name} takes the XI to ${season.league} in ${season.year}.`}</p><button className="primary" disabled={Boolean(phaseSpin)} onClick={!coach?rollCoach:!season?rollSeason:run}>{phaseSpin==="coach"?"SCOUTING MANAGERS...":phaseSpin==="league"?"DRAWING THE LEAGUE...":phaseSpin==="year"?"DRAWING THE YEAR...":!coach?"ROLL THE MANAGER":!season?"ROLL LEAGUE & YEAR":"SIMULATE THE CAMPAIGN"} <span>↗</span></button></div></section>}
  {result&&<section className={`result ${!revealFinal&&result.matches?"simulating":""}`}><div className="result-score"><span>ARCADE SCORE</span><strong>{result.score}</strong><b>{result.grade}</b></div><div className="result-main"><span className="result-kicker">SIMULATION COMPLETE · SEED {seed.slice(0,10)}</span><h2>{result.title}</h2><p>{result.story}</p><div className="stats">{result.stats.map(s=><div key={s.label}><small>{s.label}</small><b>{s.value}</b></div>)}</div>{result.matches&&result.table&&<SeasonReplay matches={result.matches} table={result.table} onComplete={()=>setRevealFinal(true)} onReset={()=>setRevealFinal(false)}/>}{result.table&&revealFinal&&<section className="season-grid"><div><div className="result-section-title"><span>FINAL TABLE</span></div><table><thead><tr><th>#</th><th>CLUB</th><th>PL</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>PTS</th></tr></thead><tbody>{result.table.map((row,i)=><tr className={row.highlight?"you":""} key={row.club}><td>{i+1}</td><td>{row.club}</td><td>{row.played}</td><td>{row.wins}</td><td>{row.draws}</td><td>{row.losses}</td><td>{row.gf}</td><td>{row.ga}</td><td>{row.gd>0?`+${row.gd}`:row.gd}</td><td><b>{row.points}</b></td></tr>)}</tbody></table></div><div><div className="result-section-title"><span>TROPHY CABINET</span></div><div className="awards">{result.awards?.map((award,i)=><div key={award}><span>{i===3?"🏆":"◆"}</span><b>{award}</b></div>)}</div></div></section>}{result.review&&revealFinal&&<TeamReview review={result.review}/>}<div className="badges">{result.badges.map(b=><span key={b}>◆ {b}</span>)}</div><ol>{result.detail.map((d,index)=><li key={d}><span>{String(index+1).padStart(2,"0")}</span>{d}</li>)}</ol><div className="actions"><button className="primary" onClick={share}>SHARE RESULT <span>↗</span></button><button className="secondary" onClick={restart}>PLAY AGAIN</button></div></div></section>}
  </main>
}
function About({go}:{go:(m:Mode)=>void}){return <main className="about"><button className="back" onClick={()=>go("home")}>← BACK TO ARCADE</button><span className="eyebrow">BEHIND THE NUMBERS</span><h1>THE MODEL IS<br/><em>HONESTLY UNREAL.</em></h1><p className="lead">Football Arcade is entertainment, not a verdict on history. Every result comes from a transparent, seeded simulation — never generative AI.</p><div className="method-grid"><article><b>01</b><h2>ORIGINAL RATINGS</h2><p>Our six attributes are independently balanced from performance, peak, longevity and positional context. They are not copied from a video game.</p></article><article><b>02</b><h2>ERA NORMALISATION</h2><p>Players are compared against the football of their own time before eras meet inside the simulation.</p></article><article><b>03</b><h2>REPEATABLE CHAOS</h2><p>A seeded probability engine makes every outcome reproducible. Same squad, same seed, same story.</p></article></div><aside><strong>THE SMALL PRINT</strong><p>Names and career facts identify players editorially. All marks, kits, badges and card visuals are original. Football Arcade is not affiliated with any player, club, league, federation or game publisher.</p></aside></main>}
export function FootballArcade(){const [mode,setMode]=useState<Mode>("home");useEffect(()=>{window.scrollTo({top:0,behavior:"smooth"})},[mode]);return <><Header go={setMode}/>{mode==="home"?<Home go={setMode}/>:mode==="about"?<About go={setMode}/>:<GameView key={mode} game={mode} go={setMode}/>}<footer><span>© 2026 FOOTBALL ARCADE</span><span>BUILT FOR THE WHAT-IFS.</span><button onClick={()=>setMode("about")}>METHODOLOGY & RIGHTS</button></footer></>}
