/* eslint-disable @next/next/no-html-link-for-pages */
"use client";

import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

type ProfileData = { username:string;display_name:string;is_public:boolean };
type Statistics = { total_runs:number;verified_runs:number;best_score:number;average_score:number;league_titles:number;invincible_seasons:number;perfect_seasons:number;total_wins:number;achievement_points:number };
type Achievement = { achievement_id:string;unlocked_at:string;achievement_definitions:{name:string;description:string;tier:string;points:number}|null };
type Run = { id:string;score:number;league_position:number;league_points:number;era:string;league_id:string;season_id:string;created_at:string };

export function PlayerProfile(){
  const [profile,setProfile]=useState<ProfileData|null>(null),[statistics,setStatistics]=useState<Statistics|null>(null),[achievements,setAchievements]=useState<Achievement[]>([]),[runs,setRuns]=useState<Run[]>([]),[status,setStatus]=useState("LOADING PLAYER LEGACY...");
  useEffect(()=>{(async()=>{const supabase=createSupabaseBrowserClient(),{data:{user}}=await supabase.auth.getUser();if(!user){window.location.replace("/account");return}const [profileResult,statisticsResult,achievementResult,runResult]=await Promise.all([supabase.from("profiles").select("username,display_name,is_public").eq("id",user.id).single(),supabase.from("user_statistics").select("*").eq("user_id",user.id).single(),supabase.from("user_achievements").select("achievement_id,unlocked_at,achievement_definitions(name,description,tier,points)").eq("user_id",user.id).order("unlocked_at",{ascending:false}),supabase.from("game_runs").select("id,score,league_position,league_points,era,league_id,season_id,created_at").eq("user_id",user.id).eq("verification_status","verified").order("created_at",{ascending:false}).limit(8)]);if(profileResult.error||statisticsResult.error){setStatus(profileResult.error?.message||statisticsResult.error?.message||"PROFILE UNAVAILABLE");return}setProfile(profileResult.data);setStatistics(statisticsResult.data);setAchievements((achievementResult.data||[]) as Achievement[]);setRuns((runResult.data||[]) as Run[]);setStatus("")})()},[]);
  if(status)return <main className="profile-page"><a className="account-back" href="/">← BACK TO ARCADE</a><h1>{status}</h1></main>;
  if(!profile||!statistics)return null;
  return <main className="profile-page"><a className="account-back" href="/">← BACK TO ARCADE</a><header className="profile-head"><div><span className="profile-kicker">FOOTBALL ARCADE PLAYER</span><h1>{profile.display_name}</h1><p>@{profile.username} · {profile.is_public?"PUBLIC PROFILE":"PRIVATE PROFILE"}</p></div><a href="/account">ACCOUNT SETTINGS ↗</a></header><section className="profile-stats"><article><span>VERIFIED RUNS</span><b>{statistics.verified_runs}</b></article><article><span>BEST SCORE</span><b>{statistics.best_score}</b></article><article><span>AVERAGE</span><b>{Number(statistics.average_score).toFixed(1)}</b></article><article><span>LEAGUE TITLES</span><b>{statistics.league_titles}</b></article><article><span>INVINCIBLE</span><b>{statistics.invincible_seasons}</b></article><article><span>ACHIEVEMENT PTS</span><b>{statistics.achievement_points}</b></article></section><section className="profile-section"><header><span>ACHIEVEMENT CABINET</span><b>{achievements.length} UNLOCKED</b></header><div className="achievement-grid">{achievements.length?achievements.map(item=><article key={item.achievement_id} className={item.achievement_definitions?.tier||"bronze"}><small>{item.achievement_definitions?.tier||"AWARD"}</small><h2>{item.achievement_definitions?.name||item.achievement_id}</h2><p>{item.achievement_definitions?.description}</p><b>+{item.achievement_definitions?.points||0} PTS</b></article>):<p className="empty-record">Complete verified Era XI runs to unlock your first achievement.</p>}</div></section><section className="profile-section"><header><span>RECENT ERA XI RUNS</span><b>{statistics.total_runs} TOTAL</b></header><div className="run-history">{runs.map(run=><article key={run.id}><strong>{run.score}</strong><div><b>{run.era.toUpperCase()} · {run.league_id} {run.season_id}</b><small>#{run.league_position} · {run.league_points} POINTS · {new Date(run.created_at).toLocaleDateString()}</small></div></article>)}</div></section></main>
}
