"use client";

import { useMemo, useState } from "react";
import playerData from "@/data/players.json";
import playerExpansion from "@/data/player-expansion.json";
import seasonData from "@/data/league-seasons.json";

type Role="GK"|"RB"|"LB"|"CB"|"DM"|"CM"|"AM"|"LM"|"RM"|"RW"|"LW"|"ST"|"CF";
type Source={name:string;pos:string;era:string;nation:string;club:string;league:string;attrs:number[]};
type Scenario={id:string;title:string;kicker:string;age:number;nationality?:string;ceiling:number;copy:string};
type Contract={club:string;league:string;level:"BREAKTHROUGH"|"PLATFORM"|"POWERHOUSE";system:string;role:string;years:number;minutes:number;copy:string};
type Season={year:number;apps:number;starts:number;goals:number;assists:number;cleanSheets:number;yellow:number;red:number;injury:string;rating:string;trophies:number;award:string;value:number;overall:number;event:string};
type Mindset={coach:number;fans:number;board:number;growth:number};

const ATTRIBUTES=["PAC","FIN","PAS","DRI","DEF","PHY"];
const POSITIONS:Role[]=["GK","RB","LB","CB","DM","CM","AM","LM","RM","RW","LW","ST","CF"];
const NATIONS=["Brazil","Argentina","England","France","Germany","Italy","Spain","Portugal","Netherlands","Nigeria","Japan","South Korea","USA","Mexico","Ghana","Croatia"];
const SCENARIOS:Scenario[]=[
  {id:"golden-ball",title:"THE GOLDEN BALL",kicker:"WONDERKID PRESSURE",age:16,ceiling:7,copy:"Start inside a giant academy with world-class potential, limited minutes and every headline watching."},
  {id:"joga-bonito",title:"THE NEXT JOGA BONITO",kicker:"BRAZILIAN WONDERKID",age:17,nationality:"Brazil",ceiling:6,copy:"Carry the expectation of Brazilian flair. Creativity opens doors, but every quiet match becomes a debate."},
  {id:"street",title:"STREET TO STADIUM",kicker:"UNKNOWN PROSPECT",age:18,ceiling:5,copy:"Begin without reputation. Smaller clubs offer real minutes and every performance changes the trajectory."},
  {id:"second-chance",title:"THE SECOND CHANCE",kicker:"RELEASED AT 20",age:20,ceiling:3,copy:"One academy already said no. Choose minutes wisely and prove the first verdict wrong."}
];
const SUBSTATS:Record<string,string[]>={PAC:["ACCELERATION","SPRINT SPEED"],FIN:["COMPOSURE","SHOT POWER"],PAS:["VISION","DELIVERY"],DRI:["BALL CONTROL","AGILITY"],DEF:["POSITIONING","TACKLING"],PHY:["STAMINA","STRENGTH"]};
const SOURCES=[...playerData,...playerExpansion] as Source[];
const LEAGUES=["Premier League","La Liga","Serie A","Bundesliga","Ligue 1"];
const SEASONS=seasonData as Array<{league:string;year:number;teams:string[]}>;

function hash(value:string){let result=2166136261;for(const char of value){result^=char.charCodeAt(0);result=Math.imul(result,16777619)}return result>>>0}
function rng(seed:string){let value=hash(seed)||1;return()=>{value^=value<<13;value^=value>>>17;value^=value<<5;return(value>>>0)/4294967296}}
function sample<T>(items:T[],count:number,seed:string){const pool=[...items],random=rng(seed),picked:T[]=[];while(pool.length&&picked.length<count)picked.push(pool.splice(Math.floor(random()*pool.length),1)[0]);return picked}
function overall(position:Role,values:number[]){
  const groups:[Role[],number[]][]=[
    [["GK"],[.04,.02,.18,.05,.48,.23]],[["CB","LB","RB"],[.13,.03,.14,.09,.38,.23]],[["DM"],[.10,.04,.24,.13,.31,.18]],
    [["CM","LM","RM"],[.12,.08,.29,.22,.13,.16]],[["AM","CF"],[.13,.20,.25,.25,.03,.14]],[["LW","RW"],[.22,.20,.17,.27,.02,.12]],[["ST"],[.17,.34,.11,.18,.02,.18]]
  ],weights=groups.find(([roles])=>roles.includes(position))?.[1]||groups[4][1];
  return Math.round(values.reduce((sum,value,index)=>sum+value*weights[index],0));
}
function generatedTags(values:number[],position:Role){
  const candidates:[[number,string],[number,string],[number,string],[number,string],[number,string],[number,string]]=[[0,"PACE ABUSER"],[1,position==="ST"?"POACHER":"GOAL THREAT"],[2,"CREATIVE PASSER"],[3,"PRESS RESISTANT"],[4,position==="GK"?"COMMANDING KEEPER":"BALL WINNER"],[5,"PHYSICAL FORCE"]];
  return candidates.filter(([index])=>values[index]>=88).sort((a,b)=>values[b[0]]-values[a[0]]).slice(0,4).map(([,tag])=>tag);
}

export function BuildPlayerCareer({onBack}:{onBack:()=>void}){
  const [stage,setStage]=useState<"setup"|"draft"|"profile"|"contracts"|"career"|"legacy">("setup");
  const [position,setPosition]=useState<Role>("ST"),[name,setName]=useState("Alex Nova"),[nationality,setNationality]=useState("Brazil"),[scenario,setScenario]=useState(SCENARIOS[0]);
  const [picks,setPicks]=useState<Array<{source:Source;value:number}>>([]),[selected,setSelected]=useState<string|null>(null),[refreshUsed,setRefreshUsed]=useState(false),[refresh,setRefresh]=useState(0);
  const [contract,setContract]=useState<Contract|null>(null),[career,setCareer]=useState<Season[]>([]),[decisionOpen,setDecisionOpen]=useState(false),[mindset,setMindset]=useState<Mindset>({coach:50,fans:50,board:50,growth:0});
  const round=picks.length,seed=`${name}-${nationality}-${position}-${scenario.id}-${round}-${refresh}`;
  const options=useMemo(()=>sample(SOURCES.filter(player=>!picks.some(pick=>pick.source.name===player.name)),5,seed),[seed,picks]);
  const values=ATTRIBUTES.map((_,index)=>picks[index]?.value||0),rating=picks.length===6?overall(position,values):0,floor=Math.max(55,rating-8),ceiling=Math.min(99,rating+scenario.ceiling),tags=generatedTags(values,position),best=values.indexOf(Math.max(...values)),weakest=values.indexOf(Math.min(...values));
  const offers=useMemo(()=>{const levels:Contract["level"][]=["BREAKTHROUGH","PLATFORM","POWERHOUSE"],systems=["4-3-3 TRANSITION","4-2-3-1 POSSESSION","3-4-2-1 HIGH PRESS"],roles=["FIRST-TEAM PROJECT","ROTATION WITH A PATH","ACADEMY / CUP OPTION"];return levels.map((level,index)=>{const league=LEAGUES[hash(seed+index)%LEAGUES.length],season=SEASONS.filter(item=>item.league===league).sort((a,b)=>b.year-a.year)[0],teams=season?.teams||["Arcade Athletic"],club=teams[level==="BREAKTHROUGH"?Math.max(0,teams.length-3):level==="PLATFORM"?Math.floor(teams.length/2):0]||teams[0];return{club,league,level,system:systems[index],role:roles[index],years:index+3,minutes:[82,58,30][index],copy:level==="BREAKTHROUGH"?"Immediate minutes, lower pressure and the fastest match development.":level==="PLATFORM"?"Competition, patience and a believable route into the starting XI.":"Elite facilities and enormous upside, but reputation must be earned."}})},[seed]);

  function randomize(){const random=rng(String(Date.now())),first=["Alex","Leo","Nico","Sami","Rafael","Noah","Kai","Milan"],last=["Nova","Silva","Costa","Moretti","Santos","Kovac","Bennett","Reyes"];setName(`${first[Math.floor(random()*first.length)]} ${last[Math.floor(random()*last.length)]}`);setNationality(NATIONS[Math.floor(random()*NATIONS.length)])}
  function lockSource(player:Source){const key=`${player.name}-${player.era}`;if(selected!==key){setSelected(key);return}setPicks(current=>[...current,{source:player,value:player.attrs[round]}]);setSelected(null);setRefresh(0)}
  function simulateSeason(){if(!contract)return;const index=career.length,random=rng(`${seed}-${contract.club}-${index}-${mindset.growth}`),current=Math.min(ceiling,rating+mindset.growth+Math.floor(index/2)),injuryRoll=random(),injury=injuryRoll>.9?"MAJOR · 10 WEEKS":injuryRoll>.72?"MINOR · 3 WEEKS":"NONE",missed=injury.startsWith("MAJOR")?9:injury.startsWith("MINOR")?3:0,chance=Math.min(94,contract.minutes+index*9+(current-75)),apps=Math.max(8,Math.round((38-missed)*chance/100+random()*5)),starts=Math.max(4,Math.round(apps*chance/110)),attacker=["ST","CF","LW","RW","AM","LM","RM"].includes(position),goals=attacker?Math.max(0,Math.round((current-65)*(position==="ST"?.55:.32)*apps/34+random()*5)):Math.round(random()*3),assists=Math.max(0,Math.round((values[2]-65)*apps/150+(["AM","CM","LM","RM","LW","RW"].includes(position)?random()*5:random()*2))),cleanSheets=["GK","CB","LB","RB","DM"].includes(position)?Math.max(0,Math.round(apps*(values[4]/150-0.28)+random()*4)):0,yellow=Math.max(0,Math.round(apps*(position==="CB"||position==="DM"?.16:.07)*random())),red=yellow>7&&random()>.8?1:0,trophies=contract.level==="POWERHOUSE"&&random()>.42?1:contract.level==="PLATFORM"&&random()>.76?1:0,average=(6.15+(current-65)/24+random()*.25).toFixed(2),value=Math.max(4,Math.round((current-60)*4.4*(apps/30))),award=Number(average)>7.45?"TEAM OF THE SEASON":goals>18?"GOLDEN BOOT RACE":cleanSheets>15?"DEFENSIVE TEAM OF THE YEAR":apps>30?"BREAKTHROUGH YEAR":"DEVELOPMENT YEAR",event=injury!=="NONE"?`${injury} interrupted the campaign, forcing a test of patience and recovery.`:apps<20?"Minutes were scarce, and the next decision became critical.":goals+assists>22?"The player became one of the league's defining attackers.":"Progress arrived through steady first-team responsibility.";setCareer(currentCareer=>[...currentCareer,{year:2026+index,apps,starts,goals,assists,cleanSheets,yellow,red,injury,rating:average,trophies,award,value,overall:current,event}]);setDecisionOpen(true)}
  function decide(type:"professional"|"bold"){setMindset(current=>type==="professional"?{coach:Math.min(100,current.coach+8),fans:Math.min(100,current.fans+2),board:Math.min(100,current.board+6),growth:current.growth+2}:{coach:Math.max(0,current.coach-3),fans:Math.min(100,current.fans+10),board:Math.max(0,current.board-2),growth:current.growth+3});setDecisionOpen(false);if(career.length>=6)setStage("legacy")}
  function restart(){setStage("setup");setPicks([]);setSelected(null);setRefreshUsed(false);setRefresh(0);setContract(null);setCareer([]);setDecisionOpen(false);setMindset({coach:50,fans:50,board:50,growth:0})}

  return <main className="game-page career-page">
    <section className="game-head"><button className="back" onClick={onBack}>← ALL GAMES</button><div><span>FOOTBALL ARCADE / CAREER MODE</span><h1>BUILD A PLAYER</h1><p>Steal six gifts. Sign the contract. Control the career.</p></div></section>
    <div className="career-steps">{["SETUP","ATTRIBUTES","PROFILE","CONTRACT","CAREER"].map((label,index)=><span className={index<=["setup","draft","profile","contracts","career","legacy"].indexOf(stage)?"active":""} key={label}><i>{index+1}</i>{label}</span>)}</div>
    {stage==="setup"&&<section className="career-setup"><span className="section-label">STEP 01 · CREATE THE PROSPECT</span><h2>EVERY CAREER<br/>NEEDS AN ORIGIN.</h2><div className="career-identity-form"><label>PLAYER NAME<input value={name} maxLength={28} onChange={event=>setName(event.target.value)}/></label><label>NATIONALITY<select value={nationality} onChange={event=>setNationality(event.target.value)}>{NATIONS.map(nation=><option key={nation}>{nation}</option>)}</select></label><button onClick={randomize}>↻ RANDOMIZE IDENTITY</button></div><div className="career-position-grid">{POSITIONS.map(role=><button className={position===role?"active":""} onClick={()=>setPosition(role)} key={role}>{role}</button>)}</div><div className="scenario-grid">{SCENARIOS.map(item=><button className={scenario.id===item.id?"active":""} onClick={()=>{setScenario(item);if(item.nationality)setNationality(item.nationality)}} key={item.id}><span>{item.kicker}</span><strong>{item.title}</strong><p>{item.copy}</p><small>START AGE {item.age} · CEILING +{item.ceiling}</small></button>)}</div><button className="primary career-next" disabled={!name.trim()} onClick={()=>setStage("draft")}>BEGIN THE ATTRIBUTE DRAFT <span>↗</span></button></section>}
    {stage==="draft"&&<section className="career-draft"><div className="career-draft-head"><div><span className="section-label">ATTRIBUTE {Math.min(round+1,6)} / 6</span><h2>{round<6?<>STEAL THEIR<br/>{ATTRIBUTES[round]}.</>:<>THE BUILD<br/>IS COMPLETE.</>}</h2><p>Five players from the entire database. Click once to select, then click again to lock the attribute.</p></div><div className="career-build-strip">{ATTRIBUTES.map((attribute,index)=><span className={index<round?"filled":index===round?"active":""} key={attribute}><small>{attribute}</small><b>{picks[index]?.value||"—"}</b><i>{picks[index]?.source.name||"UNCLAIMED"}</i></span>)}</div></div>{round<6&&<div className="career-source-cards">{options.map(player=>{const key=`${player.name}-${player.era}`;return <button className={`career-source ${selected===key?"selected":""}`} onClick={()=>lockSource(player)} key={key}><span>{player.pos} · {player.nation}</span><div>{player.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</div><h3>{player.name}</h3><p>{player.club} · {player.era}</p><strong>{player.attrs[round]} <small>{ATTRIBUTES[round]}</small></strong><i>{selected===key?"CLICK AGAIN TO LOCK":"SELECT SOURCE"}</i></button>})}</div>}<div className="career-draft-actions">{round<6&&<button disabled={refreshUsed} onClick={()=>{setRefreshUsed(true);setRefresh(value=>value+1);setSelected(null)}}>{refreshUsed?"PLAYER REFRESH USED":"↻ REFRESH THESE FIVE"}</button>}{round===6&&<button className="primary" onClick={()=>setStage("profile")}>REVEAL THE PLAYER <span>↗</span></button>}</div></section>}
    {stage==="profile"&&<section className="career-dashboard"><div className="career-card"><small>{scenario.kicker}</small><span>{name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><h2>{name}</h2><p>{nationality} · {position} · AGE {scenario.age}</p><strong>{rating}<i>OVR</i></strong><div>{tags.map(tag=><b key={tag}>{tag}</b>)}</div></div><div className="career-analysis"><span className="section-label">PLAYER DEVELOPMENT REPORT</span><h2>{ATTRIBUTES[best]} IS THE WEAPON.<br/>{ATTRIBUTES[weakest]} IS THE QUESTION.</h2><div className="development-band"><article><small>FLOOR</small><b>{floor}</b><p>Difficult adaptation or poor career choices.</p></article><article><small>CURRENT</small><b>{rating}</b><p>The player entering professional football.</p></article><article><small>CEILING</small><b>{ceiling}</b><p>Maximum outcome with minutes and smart decisions.</p></article></div><div className="career-attribute-dashboard">{ATTRIBUTES.map((attribute,index)=><article key={attribute}><div><b>{attribute}</b><strong>{values[index]}</strong></div><i style={{width:`${values[index]}%`}}/><p>{SUBSTATS[attribute].map((sub,subIndex)=><span key={sub}>{sub}<b>{Math.max(40,Math.min(99,values[index]+(subIndex?2:-2)))}</b></span>)}</p><small>FROM {picks[index]?.source.name}</small></article>)}</div><button className="primary" onClick={()=>setStage("contracts")}>ENTER THE CONTRACT ROOM <span>↗</span></button></div></section>}
    {stage==="contracts"&&<section className="contract-room"><span className="section-label">STEP 04 · CHOOSE THE FIRST MOVE</span><h2>THREE CONTRACTS.<br/>ONE CAREER.</h2><div className="contract-grid">{offers.map(offer=><article key={`${offer.club}-${offer.level}`}><span>{offer.level}</span><h3>{offer.club}</h3><p>{offer.league}</p><div><small>TACTICAL SYSTEM<b>{offer.system}</b></small><small>SQUAD ROLE<b>{offer.role}</b></small><small>PLAYING CHANCE<b>{offer.minutes}%</b></small><small>CONTRACT<b>{offer.years} YEARS</b></small></div><p>{offer.copy}</p><button onClick={()=>{setContract(offer);setStage("career")}}>SIGN THIS CONTRACT ↗</button></article>)}</div></section>}
    {(stage==="career"||stage==="legacy")&&contract&&<section className="career-hub"><div className="career-hub-head"><div><span className="section-label">{stage==="legacy"?"CAREER CHECKPOINT":"CAREER CONTROL ROOM"}</span><h2>{name}<br/><em>{contract.club}</em></h2></div><div><span><small>OVR</small><b>{career.at(-1)?.overall||rating}</b></span><span><small>AGE</small><b>{scenario.age+career.length}</b></span><span><small>VALUE</small><b>€{career.at(-1)?.value||Math.max(5,(rating-60)*3)}M</b></span></div></div><div className="relationship-bar"><span>COACH <b>{mindset.coach}</b></span><span>FANS <b>{mindset.fans}</b></span><span>BOARD <b>{mindset.board}</b></span></div>{career.length?<div className="career-timeline">{career.map(season=><article key={season.year}><span>{season.year}/{String(season.year+1).slice(2)}</span><h3>{season.award}</h3><p>{season.event}</p><div><b>{season.apps}<small>APPS</small></b><b>{season.goals}<small>GOALS</small></b><b>{season.assists}<small>ASSISTS</small></b><b>{season.cleanSheets}<small>CLEAN SHEETS</small></b><b>{season.rating}<small>AVG</small></b><b>{season.trophies}<small>TROPHIES</small></b></div><small className="career-discipline">{season.injury} INJURY · {season.yellow}Y / {season.red}R · {season.starts} STARTS</small></article>)}</div>:<div className="career-empty"><b>THE CONTRACT IS SIGNED.</b><p>Your first professional season is waiting.</p></div>}{stage==="career"&&!decisionOpen&&<button className="primary career-next" onClick={simulateSeason}>SIMULATE SEASON {2026+career.length}/{String(2027+career.length).slice(2)} <span>↗</span></button>}{decisionOpen&&<div className="career-decision"><span>MEDIA MOMENT · YOUR ANSWER CHANGES THE CAREER</span><h3>{career.at(-1)?.apps&&career.at(-1)!.apps<20?"The press asks whether you need to leave for minutes.":"The press calls you the future of the club. How do you answer?"}</h3><div><button onClick={()=>decide("professional")}><b>PROFESSIONAL</b><p>Back the coach, protect the dressing room and build trust.</p><small>+ COACH · + BOARD · STEADY GROWTH</small></button><button onClick={()=>decide("bold")}><b>BACK YOURSELF</b><p>Demand responsibility and turn pressure into momentum.</p><small>+ FANS · + DEVELOPMENT · RELATIONSHIP RISK</small></button></div></div>}{stage==="legacy"&&<div className="legacy-verdict"><span>FIRST CHAPTER COMPLETE</span><h3>{career.some(season=>season.trophies)?"A WINNER IS EMERGING.":"THE STORY IS STILL BEING WRITTEN."}</h3><p>Six seasons, {career.reduce((sum,season)=>sum+season.apps,0)} appearances, {career.reduce((sum,season)=>sum+season.goals,0)} goals and {career.reduce((sum,season)=>sum+season.trophies,0)} trophies. Future updates can extend this into transfers, money, training and deeper long-term relationships.</p><button className="primary" onClick={restart}>START A NEW CAREER <span>↗</span></button></div>}</section>}
  </main>
}
